name: Bump version and auto-release
on:
  push:
    branches:
      - main
jobs:
  call-run-python-release:
    uses: openclimatefix/.github/.github/workflows/docker-release.yml@v1.7.2
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    with:
      image_base_name: uk_pv_forecast_blend
